# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Totle < Formula
  desc "totle is a simple tool to allow developers to jot down their thoughts for safe-keeping in a transferrable format."
  homepage "https://github.com/zacowan/totle"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zacowan/totle/releases/download/v0.1.0/totle_Darwin_x86_64.tar.gz"
      sha256 "94906c8cb2c75714236c78b7d82e8b02ad70e87f53bcc997e3905e263e6699bc"

      def install
        bin.install "totle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zacowan/totle/releases/download/v0.1.0/totle_Darwin_arm64.tar.gz"
      sha256 "04b28267169ba67d5097924c2ffa7cd791400a88a9267162319eadf0d906cc24"

      def install
        bin.install "totle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zacowan/totle/releases/download/v0.1.0/totle_Linux_arm64.tar.gz"
      sha256 "8f17b58c646b2a42932120f19c390c1d006f3ddd32846ca9507a5a60dbabceb8"

      def install
        bin.install "totle"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zacowan/totle/releases/download/v0.1.0/totle_Linux_x86_64.tar.gz"
      sha256 "7c97a943b85ef8925ff0307b9c4b01b8c8491323ec1168fe043f1fb258bc8723"

      def install
        bin.install "totle"
      end
    end
  end
end
