# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Totle < Formula
  desc "totle is a simple tool to allow developers to jot down their thoughts for safe-keeping in a transferrable format."
  homepage "https://github.com/zacowan/totle"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zacowan/totle/releases/download/v0.0.10/totle_Darwin_x86_64.tar.gz"
      sha256 "4d86326f5012a87dfe3a266f091f6ede8fb7d34f85864ba7d92de6e48f5564aa"

      def install
        bin.install "totle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zacowan/totle/releases/download/v0.0.10/totle_Darwin_arm64.tar.gz"
      sha256 "a213ee9b46901dc5bd1f5685c2f296a29c3720958b0496ef42a10e26f6c40f29"

      def install
        bin.install "totle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zacowan/totle/releases/download/v0.0.10/totle_Linux_arm64.tar.gz"
      sha256 "dbdb9737b88b695fc00cc18ea13ce13eedf802dad3f70fddd960a8336f4ba950"

      def install
        bin.install "totle"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zacowan/totle/releases/download/v0.0.10/totle_Linux_x86_64.tar.gz"
      sha256 "4ce5f088b9674d0697b787cbe55527b6b0fc434ff0eed12f85278141f3c2726d"

      def install
        bin.install "totle"
      end
    end
  end
end
